import pdfplumber
import fitz  # PyMuPDF
from fpdf import FPDF
import os

def extract_text_from_pdf(pdf_path):
    """
    주어진 경로의 PDF 파일에서 텍스트를 추출합니다.
    """
    text = ""
    try:
        with pdfplumber.open(pdf_path) as pdf:
            for page in pdf.pages:
                extracted_page = page.extract_text()
                if extracted_page:
                    text += extracted_page + "\n"
    except Exception as e:
        print(f"Error extracting text from {pdf_path}: {e}")
        return None
    return text

def extract_images_from_pdf(pdf_path, temp_dir):
    """
    PDF 페이지를 이미지(도면)로 변환하여 임시 디렉토리에 저장합니다.
    """
    image_paths = []
    try:
        doc = fitz.open(pdf_path)
        for i in range(len(doc)):
            page = doc.load_page(i)
            # 특허 도면은 대개 선명해야 하므로 2배 확대(Matrix) 렌더링
            pix = page.get_pixmap(matrix=fitz.Matrix(2, 2))
            img_path = os.path.join(temp_dir, f"drawing_page_{i+1}.png")
            pix.save(img_path)
            image_paths.append(img_path)
    except Exception as e:
        print(f"Error extracting images: {e}")
    return image_paths

def create_pdf_report(content_dict, selected_items, metrics_dict=None):
    """
    선택된 분석 결과를 한글 PDF로 생성하여 바이트 데이터를 반환합니다.
    (1페이지 요약 대시보드 형태)
    """
    pdf = FPDF()
    pdf.add_page()
    
    # 1. 경로 설정: 현재 파일(utils/pdf_processor.py) 기준 상위 폴더의 fonts 폴더 참조
    base_path = os.path.dirname(os.path.abspath(__file__))
    font_dir = os.path.join(base_path, "..", "fonts") # 프로젝트 루트의 fonts 폴더
    
    font_path = os.path.join(font_dir, "malgun.ttf")
    font_bold_path = os.path.join(font_dir, "malgunbd.ttf")

    # 2. 폰트 적용 로직
    if os.path.exists(font_path):
        # 일반체 등록
        pdf.add_font("Malgun", "", font_path)
        
        # 굵은체 등록 (파일이 있으면 등록, 없으면 일반체로 대체)
        if os.path.exists(font_bold_path):
            pdf.add_font("MalgunBD", "", font_bold_path)
        else:
            pdf.add_font("MalgunBD", "", font_path)
            
        pdf.set_font("Malgun", size=11)
    else:
        # 폰트 파일이 아예 없을 경우 (최후의 수단)
        pdf.set_font("Helvetica", size=11)
        print("Warning: fonts 폴더 내에 malgun.ttf가 없습니다.")

    # 1. 헤더 (제목)
    pdf.set_font("MalgunBD", size=20)
    pdf.set_text_color(30, 70, 150)
    pdf.cell(0, 15, txt="전략적 특허 분석 요약 리포트", ln=True, align='C')
    pdf.set_font("Malgun", size=10)
    pdf.cell(0, 5, txt="(1-Page Core Strategic Summary)", ln=True, align='C')
    pdf.set_draw_color(30, 70, 150)
    pdf.line(10, 32, 200, 32)
    pdf.ln(8)

    # 2. 핵심 메트릭 요약 (그리드 형태)
    if metrics_dict:
        pdf.set_fill_color(240, 245, 255)
        pdf.set_font("MalgunBD", size=10)
        pdf.set_text_color(70, 70, 70)
        
        # 첫 번째 줄
        pdf.cell(45, 10, txt="  권리 범위", border=1, fill=True)
        pdf.set_font("Malgun", size=10)
        pdf.cell(50, 10, txt=f" {metrics_dict.get('claims', '미검출')}", border=1)
        
        pdf.set_font("MalgunBD", size=10)
        pdf.cell(45, 10, txt="  출원인", border=1, fill=True)
        pdf.set_font("Malgun", size=10)
        pdf.cell(50, 10, txt=f" {metrics_dict.get('applicant', '미상')}", border=1, ln=True)
        
        # 두 번째 줄
        pdf.set_font("MalgunBD", size=10)
        pdf.cell(45, 10, txt="  도면 수", border=1, fill=True)
        pdf.set_font("Malgun", size=10)
        pdf.cell(50, 10, txt=f" {metrics_dict.get('drawings', '미검출')}", border=1)
        
        pdf.set_font("MalgunBD", size=10)
        pdf.cell(45, 10, txt="  핵심 키워드", border=1, fill=True)
        pdf.set_font("Malgun", size=10)
        # 키워드가 너무 길면 잘라줌
        keywords = metrics_dict.get('keywords', '')
        if len(keywords) > 25: keywords = keywords[:22] + "..."
        pdf.cell(50, 10, txt=f" {keywords}", border=1, ln=True)
        pdf.ln(8)

    # 3. 상세 분석 섹션
    for item_name, display_name in [("summary", "요약 분석"), ("strategy", "방어 전략"), ("solution", "해결 방안")]:
        if item_name in selected_items and content_dict.get(item_name):
            # 섹션 헤더
            pdf.set_font("MalgunBD", size=13)
            pdf.set_text_color(30, 70, 150)
            pdf.set_fill_color(230, 240, 255)
            pdf.cell(0, 8, txt=f"  {display_name}", ln=True, fill=True)
            pdf.ln(2)
            
            # 본문
            pdf.set_font("Malgun", size=10) # 9에서 10으로 확대
            pdf.set_text_color(30, 30, 30)
            
            # 텍스트 정제 (Markdown 기호 제거 및 줄바꿈 최적화)
            text = content_dict[item_name]
            text = text.replace("**", "").replace("#", "").strip()
            # 1페이지를 위해 너무 긴 경우 앞부분만 (함축되었으므로 보통 짧겠지만 안전용)
            if len(text) > 1000:
                text = text[:970] + "... (이하 생략)"
                
            pdf.multi_cell(0, 7, txt=text)
            pdf.ln(5)

    # 하단 푸터 (생성일 등)
    import datetime
    pdf.set_y(-20)
    pdf.set_font("Malgun", size=8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, txt=f"Generated by Intelligent Patent Analysis Platform | {datetime.datetime.now().strftime('%Y-%m-%d')}", align='C')

    return bytes(pdf.output())
