[theme]
base = "light"
primaryColor = "#2563eb"
backgroundColor = "#f8f9fb"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"


#[server]
#enableXsrfProtection = false
#enableCORS = false
#maxUploadSize = 500
